services:
  _defaults:
    autowire: true
    autoconfigure: true
    public: false

  Vancado\VncPowermailEncrypt\EventListener\EncryptMailEvent:
    tags:
      - name: event.listener
        identifier: 'vncpowermailencrypt/encryptmail'